### PR TITLE
Create metadata.yaml

### PR DESCRIPTION
**Pull request by david-gold-is24**

### CODE REVIEW

**Comment by laiph** [comment]
I think you also need to add `data_protection_relevant: false`
It's not present in the metadata.yml documentation, but I remember I've talked with Enrico at some point and this was required by the automated crawler to avoid having the project being a subject to audit.

**Comment by david-gold-is24** [comment]
> I think you also need to add `data_protection_relevant: false`
> It's not present in the metadata.yml documentation, but I remember I've talked with Enrico at some point and this was required by the automated crawler to avoid having the project being a subject for data protection audit.

This is covered by the confidentiality attribute. This is stating at the moment, that no PII is processed or persisted in this application. Is this correct?

**Comment by laiph** [comment]
This is what I thought so too, then Enrico told me to add that field as well. This was few months back, maybe it's not needed anymore?

**Comment by david-gold-is24** [comment]
AFAIK, it is not needed anymore

**Pull request merged**
